workflows:
  ios-build:
    name: iOS Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods

    scripts:
      - name: Clean Flutter project
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: Generate Podfile if missing
        script: |
          set -e
          cd ios
          flutter build ios --no-codesign

      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod install --repo-update --verbose

      - name: Build iOS App
        script: |
          set -e
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/debug-iphoneos/*.app
